import os

files_to_include = [
  "supabase-schema.sql",
  "add-properties-rls-policies.sql",
  "add-properties-features.sql",
  "add-wallet-address-column.sql",
  "add-property-removal-tracking.sql",
  "add-inquiries-table.sql",
  "add-inquiry-replies-table.sql",
  "add-offers-table.sql",
  "add-transactions-table.sql",
  "notifications-migration.sql",
  "migration-add-blockchain-columns.sql",
  "migration-add-nft-columns.sql",
  "migration-add-listing-type.sql",
  "migration-add-survey-number.sql",
  "migration-add-registration-number.sql",
  "migration-add-registration-id.sql",
  "migration-add-required-documents.sql",
  "migration-add-profile-documents.sql",
  "storage-property-images-setup-fixed.sql",
  "migration-registration-documents-storage-policies-simple.sql"
]

final_sql = "-- Initial Migration Schema generated by AI\n\n"

for file in files_to_include:
    file_path = os.path.join('_legacy_sql', file)
    if os.path.exists(file_path):
        final_sql += f"-- ========================\n-- FILE: {file}\n-- ========================\n\n"
        with open(file_path, 'r', encoding='utf-8') as f:
            final_sql += f.read()
            final_sql += '\n\n'
    else:
        print(f"Warning: {file} not found.")

os.makedirs('supabase/migrations', exist_ok=True)
with open('supabase/migrations/20260418000000_init.sql', 'w', encoding='utf-8') as out_f:
    out_f.write(final_sql)
print("Migration built successfully at supabase/migrations/20260418000000_init.sql")

# Build Seed
seed_files = ["sample-data-pune.sql", "sample-rental-data.sql"]
seed_sql = "-- Database Seed File\n\n"
for sfile in seed_files:
    file_path = os.path.join('_legacy_sql', sfile)
    if os.path.exists(file_path):
        seed_sql += f"-- FILE: {sfile}\n"
        with open(file_path, 'r', encoding='utf-8') as f:
            seed_sql += f.read()
            seed_sql += '\n\n'

with open('supabase/seed.sql', 'w', encoding='utf-8') as out_f:
    out_f.write(seed_sql)
print("Seed file built successfully at supabase/seed.sql")
