/* eslint-env node */
const fs = require('fs');
const path = require('path');

const filesToInclude = [
  "supabase-schema.sql",
  "add-properties-rls-policies.sql",
  "add-properties-features.sql",
  "add-wallet-address-column.sql",
  "add-property-removal-tracking.sql",
  "add-inquiries-table.sql",
  "add-inquiry-replies-table.sql",
  "add-offers-table.sql",
  "add-transactions-table.sql",
  "notifications-migration.sql",
  
  // Blockchain migrations
  "migration-add-blockchain-columns.sql",
  "migration-add-nft-columns.sql",
  "migration-add-listing-type.sql",
  
  // Registration documents
  "migration-add-survey-number.sql",
  "migration-add-registration-number.sql",
  "migration-add-registration-id.sql",
  "migration-add-required-documents.sql",
  "migration-add-profile-documents.sql",
  
  // Storage and policies
  "storage-property-images-setup-fixed.sql",
  "migration-registration-documents-storage-policies-simple.sql"
];

let finalSql = "-- Initial Migration Schema generated by AI\n\n";

for (const file of filesToInclude) {
  const filePath = path.join('_legacy_sql', file);
  if (fs.existsSync(filePath)) {
    finalSql += `-- ========================\n-- FILE: ${file}\n-- ========================\n\n`;
    finalSql += fs.readFileSync(filePath, 'utf8');
    finalSql += '\n\n';
  } else {
    console.warn(`Warning: ${file} not found.`);
  }
}

fs.writeFileSync('supabase/migrations/20260418000000_init.sql', finalSql);
console.log('Migration built successfully at supabase/migrations/20260418000000_init.sql');
