-- Initial Migration Schema generated by AI
-- PRISTINE DECLARATIVE SCHEMA

-- Profiles table (uses TEXT for Clerk User IDs)
CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY,
  full_name TEXT,
  phone TEXT,
  wallet_address TEXT,
  is_admin BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_profiles_is_admin ON profiles(is_admin) WHERE is_admin = true;

-- Properties table
CREATE TABLE IF NOT EXISTS properties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT, -- Clerk user ID
  title TEXT NOT NULL,
  location TEXT NOT NULL,
  address TEXT,
  price DECIMAL(12, 2) NOT NULL,
  bedrooms INTEGER DEFAULT 0,
  bathrooms INTEGER DEFAULT 0,
  sqft INTEGER,
  year_built INTEGER,
  type TEXT NOT NULL, 
  listing_type TEXT DEFAULT 'sale', -- 'sale' or 'rent'
  description TEXT,
  features TEXT[],
  images TEXT[],
  featured BOOLEAN DEFAULT false,
  view_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'paused', 'sold', 'rented')),
  blockchain_property_id TEXT,
  blockchain_tx_hash TEXT,
  nft_token_id TEXT,
  nft_contract_address TEXT,
  nft_token_uri TEXT,
  nft_mint_tx_hash TEXT,
  nft_transfer_tx_hash TEXT,
  removed_by TEXT,
  removed_at TIMESTAMP WITH TIME ZONE,
  removal_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_properties_status ON properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_view_count ON properties(view_count);
CREATE INDEX IF NOT EXISTS idx_properties_blockchain_id ON properties(blockchain_property_id);
CREATE INDEX IF NOT EXISTS idx_properties_nft_token_id ON properties(nft_token_id);
CREATE INDEX IF NOT EXISTS idx_properties_nft_contract_address ON properties(nft_contract_address);
CREATE INDEX IF NOT EXISTS idx_properties_removed_at ON properties(removed_at) WHERE removed_at IS NOT NULL;

-- Registrations table
CREATE TABLE IF NOT EXISTS registrations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  property_type TEXT NOT NULL,
  property_address TEXT NOT NULL,
  property_size INTEGER,
  property_description TEXT,
  owner_name TEXT NOT NULL,
  owner_email TEXT NOT NULL,
  owner_phone TEXT NOT NULL,
  owner_id_number TEXT NOT NULL,
  survey_number TEXT,
  registration_number TEXT,
  registration_id TEXT,
  documents TEXT[], 
  status TEXT DEFAULT 'pending',
  reviewed_by TEXT,
  reviewed_at TIMESTAMP WITH TIME ZONE,
  review_notes TEXT,
  estimated_review_days INTEGER DEFAULT 5,
  submitted_date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  estimated_completion_date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Saved properties table
CREATE TABLE IF NOT EXISTS saved_properties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  property_id UUID REFERENCES properties(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(user_id, property_id)
);

-- Inquiries table
CREATE TABLE IF NOT EXISTS inquiries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  property_id UUID REFERENCES properties(id) ON DELETE CASCADE NOT NULL,
  user_id TEXT, 
  buyer_name TEXT NOT NULL,
  buyer_email TEXT NOT NULL,
  buyer_phone TEXT,
  message TEXT,
  status TEXT DEFAULT 'new',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_inquiries_property_id ON inquiries(property_id);
CREATE INDEX IF NOT EXISTS idx_inquiries_user_id ON inquiries(user_id);
CREATE INDEX IF NOT EXISTS idx_inquiries_status ON inquiries(status);

-- Inquiry_replies table
CREATE TABLE IF NOT EXISTS inquiry_replies (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  inquiry_id UUID REFERENCES inquiries(id) ON DELETE CASCADE NOT NULL,
  sender_id TEXT NOT NULL, 
  sender_type TEXT NOT NULL CHECK (sender_type IN ('owner', 'buyer')),
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_inquiry_replies_inquiry_id ON inquiry_replies(inquiry_id);
CREATE INDEX IF NOT EXISTS idx_inquiry_replies_sender_id ON inquiry_replies(sender_id);
CREATE INDEX IF NOT EXISTS idx_inquiry_replies_created_at ON inquiry_replies(created_at);

-- Property_offers table
CREATE TABLE IF NOT EXISTS property_offers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  property_id UUID REFERENCES properties(id) ON DELETE CASCADE NOT NULL,
  buyer_id TEXT NOT NULL,
  seller_id TEXT NOT NULL, 
  offer_amount DECIMAL(12, 2) NOT NULL,
  currency TEXT DEFAULT 'INR',
  offer_type TEXT NOT NULL CHECK (offer_type IN ('purchase', 'rental')), 
  status TEXT DEFAULT 'pending', 
  message TEXT, 
  expires_at TIMESTAMP WITH TIME ZONE, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_property_offers_property_id ON property_offers(property_id);
CREATE INDEX IF NOT EXISTS idx_property_offers_buyer_id ON property_offers(buyer_id);
CREATE INDEX IF NOT EXISTS idx_property_offers_seller_id ON property_offers(seller_id);
CREATE INDEX IF NOT EXISTS idx_property_offers_status ON property_offers(status);
CREATE INDEX IF NOT EXISTS idx_property_offers_created_at ON property_offers(created_at DESC);

-- Transactions table
CREATE TABLE IF NOT EXISTS transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL, 
  property_id UUID REFERENCES properties(id) ON DELETE SET NULL,
  transaction_type TEXT NOT NULL, 
  amount DECIMAL(12, 2) NOT NULL,
  currency TEXT DEFAULT 'INR',
  status TEXT DEFAULT 'pending', 
  description TEXT,
  blockchain_tx_hash TEXT, 
  metadata JSONB, 
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_property_id ON transactions(property_id);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(status);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON transactions(created_at DESC);

-- Notifications table
CREATE TABLE IF NOT EXISTS notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  type TEXT NOT NULL, 
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  link TEXT, 
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  read_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(user_id, read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);

-- ============================================================================
-- HELPER FUNCTIONS FOR RLS POLICIES (CLERK INTEGRATION)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.clerk_user_id() 
RETURNS TEXT AS $$
  SELECT COALESCE(
    current_setting('request.jwt.claims', true)::json->>'sub',
    current_setting('request.jwt.claims', true)::json->>'user_id',
    current_setting('request.jwt.claims', true)::json->>'id',
    current_setting('request.jwt.claims', true)::json->>'clerk_user_id',
    current_setting('request.jwt.claims', true)::json->'user'->>'id',
    current_setting('request.jwt.claims', true)::json->'claims'->>'sub',
    current_setting('request.jwt.claims', true)::json->'claims'->>'user_id'
  );
$$ LANGUAGE SQL STABLE;

CREATE OR REPLACE FUNCTION public.is_admin(user_id_param TEXT)
RETURNS BOOLEAN AS $$
  SELECT COALESCE(
    (SELECT is_admin FROM profiles WHERE id = user_id_param),
    false
  );
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.clerk_user_id() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(TEXT) TO authenticated;

-- ============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE inquiry_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE property_offers ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Property Policies
DROP POLICY IF EXISTS "Properties are viewable by everyone" ON properties;
CREATE POLICY "Properties are viewable by everyone" ON properties FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can create properties" ON properties;
CREATE POLICY "Users can create properties" ON properties FOR INSERT WITH CHECK (
  (public.clerk_user_id() IS NOT NULL AND public.clerk_user_id() = user_id) OR
  (current_setting('request.jwt.claims', true) IS NOT NULL AND user_id IS NOT NULL)
);
DROP POLICY IF EXISTS "Users can update own properties or admins update any" ON properties;
CREATE POLICY "Users can update own properties or admins update any" ON properties FOR UPDATE USING (
  public.clerk_user_id() = user_id OR public.is_admin(public.clerk_user_id())
) WITH CHECK (public.clerk_user_id() = user_id OR public.is_admin(public.clerk_user_id()));
DROP POLICY IF EXISTS "Users can delete own properties or admins delete any" ON properties;
CREATE POLICY "Users can delete own properties or admins delete any" ON properties FOR DELETE USING (
  public.clerk_user_id() = user_id OR public.is_admin(public.clerk_user_id())
);

-- Profile Policies
DROP POLICY IF EXISTS "Users can view own profile or admins view all" ON profiles;
CREATE POLICY "Users can view own profile or admins view all" ON profiles FOR SELECT USING (
  public.clerk_user_id() = id OR public.is_admin(public.clerk_user_id())
);
DROP POLICY IF EXISTS "Users can update own profile or admins update any" ON profiles;
CREATE POLICY "Users can update own profile or admins update any" ON profiles FOR UPDATE USING (
  public.clerk_user_id() = id OR public.is_admin(public.clerk_user_id())
) WITH CHECK (public.clerk_user_id() = id OR public.is_admin(public.clerk_user_id()));
DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (public.clerk_user_id() = id);

-- Registration Policies
DROP POLICY IF EXISTS "Users can view own registrations or admins view all" ON registrations;
CREATE POLICY "Users can view own registrations or admins view all" ON registrations FOR SELECT USING (
  public.clerk_user_id() = user_id OR public.is_admin(public.clerk_user_id())
);
DROP POLICY IF EXISTS "Users can create own registrations" ON registrations;
CREATE POLICY "Users can create own registrations" ON registrations FOR INSERT WITH CHECK (public.clerk_user_id() = user_id);
DROP POLICY IF EXISTS "Users can update own registrations or admins update any" ON registrations;
CREATE POLICY "Users can update own registrations or admins update any" ON registrations FOR UPDATE USING (
  public.clerk_user_id() = user_id OR public.is_admin(public.clerk_user_id())
) WITH CHECK (public.clerk_user_id() = user_id OR public.is_admin(public.clerk_user_id()));

-- Saved Properties Policies
DROP POLICY IF EXISTS "Users can view own saved properties" ON saved_properties;
CREATE POLICY "Users can view own saved properties" ON saved_properties FOR SELECT USING (public.clerk_user_id() = user_id);
DROP POLICY IF EXISTS "Users can save properties" ON saved_properties;
CREATE POLICY "Users can save properties" ON saved_properties FOR INSERT WITH CHECK (public.clerk_user_id() = user_id);
DROP POLICY IF EXISTS "Users can remove saved properties" ON saved_properties;
CREATE POLICY "Users can remove saved properties" ON saved_properties FOR DELETE USING (public.clerk_user_id() = user_id);

-- Inquiries Policies
DROP POLICY IF EXISTS "Property owners can view their property inquiries" ON inquiries;
CREATE POLICY "Property owners can view their property inquiries" ON inquiries FOR SELECT USING (
  EXISTS (SELECT 1 FROM properties WHERE properties.id = inquiries.property_id AND properties.user_id = public.clerk_user_id())
);
DROP POLICY IF EXISTS "Users can create inquiries" ON inquiries;
CREATE POLICY "Users can create inquiries" ON inquiries FOR INSERT WITH CHECK (user_id IS NULL OR user_id = public.clerk_user_id());
DROP POLICY IF EXISTS "Property owners can update inquiry status" ON inquiries;
CREATE POLICY "Property owners can update inquiry status" ON inquiries FOR UPDATE USING (
  EXISTS (SELECT 1 FROM properties WHERE properties.id = inquiries.property_id AND properties.user_id = public.clerk_user_id())
);

-- Inquiry Replies Policies
DROP POLICY IF EXISTS "Owners can view replies to their property inquiries" ON inquiry_replies;
CREATE POLICY "Owners can view replies to their property inquiries" ON inquiry_replies FOR SELECT USING (
  EXISTS (SELECT 1 FROM inquiries INNER JOIN properties ON properties.id = inquiries.property_id WHERE inquiry_replies.inquiry_id = inquiries.id AND properties.user_id = public.clerk_user_id())
);
DROP POLICY IF EXISTS "Buyers can view replies to their inquiries" ON inquiry_replies;
CREATE POLICY "Buyers can view replies to their inquiries" ON inquiry_replies FOR SELECT USING (
  EXISTS (SELECT 1 FROM inquiries WHERE inquiry_replies.inquiry_id = inquiries.id AND inquiries.user_id = public.clerk_user_id())
);
DROP POLICY IF EXISTS "Owners can create replies" ON inquiry_replies;
CREATE POLICY "Owners can create replies" ON inquiry_replies FOR INSERT WITH CHECK (
  sender_type = 'owner' AND EXISTS (SELECT 1 FROM inquiries INNER JOIN properties ON properties.id = inquiries.property_id WHERE inquiry_replies.inquiry_id = inquiries.id AND properties.user_id = public.clerk_user_id() AND sender_id = public.clerk_user_id())
);
DROP POLICY IF EXISTS "Buyers can create replies" ON inquiry_replies;
CREATE POLICY "Buyers can create replies" ON inquiry_replies FOR INSERT WITH CHECK (
  sender_type = 'buyer' AND EXISTS (SELECT 1 FROM inquiries WHERE inquiry_replies.inquiry_id = inquiries.id AND inquiries.user_id = public.clerk_user_id() AND sender_id = public.clerk_user_id())
);

-- Property Offers Policies
DROP POLICY IF EXISTS "Buyers can view own offers" ON property_offers;
CREATE POLICY "Buyers can view own offers" ON property_offers FOR SELECT USING (buyer_id = public.clerk_user_id());
DROP POLICY IF EXISTS "Sellers can view offers for their properties" ON property_offers;
CREATE POLICY "Sellers can view offers for their properties" ON property_offers FOR SELECT USING (seller_id = public.clerk_user_id());
DROP POLICY IF EXISTS "Buyers can create offers" ON property_offers;
CREATE POLICY "Buyers can create offers" ON property_offers FOR INSERT WITH CHECK (buyer_id = public.clerk_user_id() OR current_setting('request.jwt.claims', true) IS NOT NULL);
DROP POLICY IF EXISTS "Sellers can update offer status" ON property_offers;
CREATE POLICY "Sellers can update offer status" ON property_offers FOR UPDATE USING (seller_id = public.clerk_user_id()) WITH CHECK (seller_id = public.clerk_user_id());
DROP POLICY IF EXISTS "Buyers can withdraw offers" ON property_offers;
CREATE POLICY "Buyers can withdraw offers" ON property_offers FOR UPDATE USING (buyer_id = public.clerk_user_id()) WITH CHECK (buyer_id = public.clerk_user_id() AND status = 'withdrawn');

-- Transactions Policies
DROP POLICY IF EXISTS "Users can view own transactions" ON transactions;
CREATE POLICY "Users can view own transactions" ON transactions FOR SELECT USING (user_id = public.clerk_user_id());
DROP POLICY IF EXISTS "Users can create own transactions" ON transactions;
CREATE POLICY "Users can create own transactions" ON transactions FOR INSERT WITH CHECK (user_id = public.clerk_user_id() OR current_setting('request.jwt.claims', true) IS NOT NULL);
DROP POLICY IF EXISTS "Users can update own transactions" ON transactions;
CREATE POLICY "Users can update own transactions" ON transactions FOR UPDATE USING (user_id = public.clerk_user_id()) WITH CHECK (user_id = public.clerk_user_id());

-- Notifications Policies
DROP POLICY IF EXISTS "Users can view own notifications" ON notifications;
CREATE POLICY "Users can view own notifications" ON notifications FOR SELECT USING (public.clerk_user_id() = user_id);
DROP POLICY IF EXISTS "Users can update own notifications" ON notifications;
CREATE POLICY "Users can update own notifications" ON notifications FOR UPDATE USING (public.clerk_user_id() = user_id) WITH CHECK (public.clerk_user_id() = user_id);
DROP POLICY IF EXISTS "Users can insert own notifications or admins insert any" ON notifications;
CREATE POLICY "Users can insert own notifications or admins insert any" ON notifications FOR INSERT WITH CHECK (
  public.clerk_user_id() = user_id OR public.is_admin(public.clerk_user_id())
);

-- ============================================================================
-- STORAGE POLICIES
-- ============================================================================

DO $$
BEGIN
  INSERT INTO storage.buckets (id, name, public) VALUES ('property-images', 'property-images', true) ON CONFLICT (id) DO NOTHING;
  INSERT INTO storage.buckets (id, name, public) VALUES ('registration-documents', 'registration-documents', true) ON CONFLICT (id) DO NOTHING;
END $$;

-- Removed storage.objects ALTER to prevent permission errors

DROP POLICY IF EXISTS "Users can upload property images" ON storage.objects;
CREATE POLICY "Users can upload property images" ON storage.objects FOR INSERT TO authenticated WITH CHECK (
  bucket_id = 'property-images' AND (current_setting('request.jwt.claims', true) IS NOT NULL OR auth.uid() IS NOT NULL)
);
DROP POLICY IF EXISTS "Public can view property images" ON storage.objects;
CREATE POLICY "Public can view property images" ON storage.objects FOR SELECT TO public USING (bucket_id = 'property-images');
DROP POLICY IF EXISTS "Users can update their own property images" ON storage.objects;
CREATE POLICY "Users can update their own property images" ON storage.objects FOR UPDATE TO authenticated USING (
  bucket_id = 'property-images' AND (current_setting('request.jwt.claims', true) IS NOT NULL OR auth.uid() IS NOT NULL)
) WITH CHECK (bucket_id = 'property-images' AND (current_setting('request.jwt.claims', true) IS NOT NULL OR auth.uid() IS NOT NULL));
DROP POLICY IF EXISTS "Users can delete their own property images" ON storage.objects;
CREATE POLICY "Users can delete their own property images" ON storage.objects FOR DELETE TO authenticated USING (
  bucket_id = 'property-images' AND (current_setting('request.jwt.claims', true) IS NOT NULL OR auth.uid() IS NOT NULL)
);

DROP POLICY IF EXISTS "Public can view registration documents" ON storage.objects;
CREATE POLICY "Public can view registration documents" ON storage.objects FOR SELECT TO public USING (bucket_id = 'registration-documents');
DROP POLICY IF EXISTS "Users can upload registration documents" ON storage.objects;
CREATE POLICY "Users can upload registration documents" ON storage.objects FOR INSERT TO authenticated WITH CHECK (
  bucket_id = 'registration-documents' AND (current_setting('request.jwt.claims', true) IS NOT NULL OR auth.uid() IS NOT NULL)
);
DROP POLICY IF EXISTS "Users can update registration documents" ON storage.objects;
CREATE POLICY "Users can update registration documents" ON storage.objects FOR UPDATE TO authenticated USING (
  bucket_id = 'registration-documents' AND (current_setting('request.jwt.claims', true) IS NOT NULL OR auth.uid() IS NOT NULL)
) WITH CHECK (bucket_id = 'registration-documents' AND (current_setting('request.jwt.claims', true) IS NOT NULL OR auth.uid() IS NOT NULL));
DROP POLICY IF EXISTS "Users can delete registration documents" ON storage.objects;
CREATE POLICY "Users can delete registration documents" ON storage.objects FOR DELETE TO authenticated USING (
  bucket_id = 'registration-documents' AND (current_setting('request.jwt.claims', true) IS NOT NULL OR auth.uid() IS NOT NULL)
);
